### ISSUE TITLE
How to use block constants ?

### ISSUE THREAD

**Issue by Pholith** [str1z/mlogjs#3]
Is it possible to use @thisx, @thisy, @links or getlink ? And how to do it if it is?
https://mindustrygame.github.io/wiki/logic/3-variables/#processor-variables-and-constants

**Comment by str1z** [comment]
Yes, it is totally possible to use block constants using the template literal syntax in JavaScript.
`print(\`@thisx\`)`

**Comment by str1z** [comment]
This will be fixed in 0.1.0. I will start working on it now. I am so sorry.

**Comment by Pholith** [comment]
Fine, this seems to works, thanks ! It should be nice to add it to the doc.

**Comment by Pholith** [comment]
It's a pity to have been forced to remove such an important feature to put the @, it would have been great to be able to write this.thisx to have an @.

**Comment by str1z** [comment]
Yep, but no worries. I am working on the 0.2.0v which has a lot more features. Stack memory, arrays, inline functions and more.

**Comment by str1z** [comment]
API changed, and it is now possible with `Store("@thisx")`.
